version: '3.8'

services:
  python_app:
    image: python:3
    working_dir: /usr/src/app
    volumes:
      - .:/usr/src/app
    ports:
      - "5000:5000"
    command: >
      sh -c "pip install --no-cache-dir -r requirements.txt && python app.py"
